[tool.mypy]
python_version = '3.7'
ignore_missing_imports = true
namespace_packages = true

[[tool.mypy.overrides]]
module = ["github.*"]
check_untyped_defs = true
disallow_untyped_defs = true


[tool.black]
# https://github.com/psf/black
line-length = 120
target-version = ['py37']

[tool.docformatter]
recursive = true
wrap-summaries = 120
wrap-descriptions = 120
blank = true


[tool.ruff]
line-length = 120
target-version = "py37"
# Enable Pyflakes `E` and `F` codes by default.
select = [
    "E", "W",  # see: https://pypi.org/project/pycodestyle
    "F",  # see: https://pypi.org/project/pyflakes
    "I",  # see: isort
]
ignore = [
    "E501",
    "E741",
]
ignore-init-module-imports = true
unfixable = ["F401"]
