[tool.mypy]
python_version = '3.7'
ignore_missing_imports = true
namespace_packages = true

[[tool.mypy.overrides]]
module = ["github.*"]
check_untyped_defs = true
disallow_untyped_defs = true
warn_no_return = false

[tool.black]
# https://github.com/psf/black
line-length = 120
target-version = ['py37']


[tool.codespell]
skip = 'pyproject.toml,tests/*'
quiet-level = 3
# comma separated list of words; waiting for:
#  https://github.com/codespell-project/codespell/issues/2839#issuecomment-1731601603
# also adding links until they ignored by its: nature
#  https://github.com/codespell-project/codespell/issues/2243#issuecomment-1732019960
ignore-words-list = "Manuel"


[tool.ruff]
line-length = 120
target-version = "py37"
# Enable Pyflakes `E` and `F` codes by default.
select = [
    "E", "W",  # see: https://pypi.org/project/pycodestyle
    "F",  # see: https://pypi.org/project/pyflakes
    "I",  # see: isort
]
ignore = [
    "E501",
    "E741",
]
ignore-init-module-imports = true
unfixable = ["F401"]
